# This is a basic workflow to help you get started with Actions

name: DevOps-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# env:
  # DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }} # developernomis
  # DOCKERHUB_PASSWORD: ${{ env.DOCKERHUB_PASSWORD }} # 607d4ade-3300-477e-8b0d-3081f09e3f9d

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the jo
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK-11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile and build jar-file
        working-directory: ./cicd-drone
        run: mvn assembly:assembly
        

  test:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Unit Tests
        working-directory: ./cicd-drone
        run: mvn test
      - name: install pmd
        uses: sfdx-actions/setup-pmd@v1
      
      - name: static code analysis
        working-directory: ./cicd-drone
        run: pmd -d src/main/java -f text -R pmd_ruleset.xml -language xml
        
        
        
  deploy:
    runs-on: ubuntu-latest
    
    steps:
        
      - uses: actions/checkout@v3
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: print out name
        run: echo 'Test'
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Print workdir
        working-directory: cicd-drone/target
        run: pwd
      -
        name: Build and push 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: developernomis/calculator_test:latest
