# This is a basic workflow to help you get started with Actions

name: DevOps

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK-11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile and build jar-file
        working-directory: ./cicd-drone
        run: mvn assembly:assembly
        

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Unit Tests
        run: mvn test
      
      - name: static code analysis
        run: pmd -d src/main/java -f text -R pmd_ruleset.xml --force-language xml
        
        
        
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Publish to DockerHub
        uses: docker/login-action@v1
        with: 
          registry: ${{ env.DOCKER_HUB_Registry }}
          username: ${{ env.DOCKER_HUB_Username }}
          password: ${{ env.DOCKER_HUB }}
